# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3c2d502a-4144-4b9f-b196-38114e73ab53";
      fsType = "btrfs";
      options = [ "subvol=nixos-root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3c2d502a-4144-4b9f-b196-38114e73ab53";
      fsType = "btrfs";
      options = [ "subvol=nixos-home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C18C-848C";
      fsType = "vfat";
    };

  fileSystems."/mnt/backup_ssd" =
    { device = "/dev/disk/by-uuid/f86a0417-2560-452b-9074-84a75739e41e";
      fsType = "btrfs";
      options = [ "subvolid=5" "nofail" "x-systemd.automount" "x-systemd.device-timeout=1ms" "x-systemd.idle-timeout=1min" ];
    };

  fileSystems."/mnt/btr_pool" =
    { device = "/dev/disk/by-uuid/3c2d502a-4144-4b9f-b196-38114e73ab53";
      fsType = "btrfs";
      options = [ "subvolid=5" "noatime" ];
    };



  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
